
[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 3900
solc_version = "0.8.25"
evm_version="Cancun"
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
line_length = 80

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
base = "https://mainnet.base.org"
localhost = "http://127.0.0.1:8545"

